import type { Lesson, Module, Track } from "@/lib/content/types";

export const verificationTrack: Track = {
  id: "verification",
  slug: "verification",
  title: "Verification",
  shortTitle: "Verification",
  description:
    "An intermediate course on AI verification: the technical, institutional, and legal mechanisms that make agreements mutually trustable and enforceable.",
  kind: "governance",
  moduleIds: ["v-why", "v-scoping", "v-infrastructure", "v-covert", "v-capstone"],
  prerequisiteEnforcement: "soft",
  chunkedReading: false,
};

export const verificationModules: Module[] = [
  {
    id: "v-why",
    slug: "why-verification",
    trackId: "verification",
    title: "Why are we teaching this?",
    summary:
      "The oldest problem in arms control, applied to AI: when you sign a mutual agreement, how do you know the other party will uphold it? Opens with the welcome and the course's own framing, then the case that ASI risk warrants an agreement at all, why successful prevention is invisible, the intuitions a verification regime runs on, and seven decades of arms-control precedent.",
    order: 0,
    prerequisiteModuleIds: [],
    itemIds: [
      "v-welcome",
      "v-introduction",
      "v-prevention",
      "v-theories-of-change",
      "v-intuitions",
      "v-precedents",
      "v-strategic-foundations",
    ],
  },
  {
    id: "v-scoping",
    slug: "policy-scoping",
    trackId: "verification",
    title: "Policy scoping & actors",
    summary:
      "What kind of policy are we trying to verify, and who does a treaty rely upon, apply to, and constrain? Compute versus capability thresholds, the effectiveness/feasibility pair, the anatomy of a pause agreement, and the actor map across the compute supply chain.",
    order: 1,
    prerequisiteModuleIds: ["v-why"],
    itemIds: [
      "v-scoping-intro",
      "v-scoping-thresholds",
      "v-scoping-effective-feasible",
      "v-scoping-anatomy",
      "v-paper-scher-treaty",
      "v-scoping-actors",
      "v-interactive-map",
      "v-actor-edges",
      "v-scoping-upstream-downstream",
      "v-context-distiller",
    ],
  },
  {
    id: "v-infrastructure",
    slug: "verification-infrastructure",
    trackId: "verification",
    title: "Verification infrastructure and evidence streams",
    summary:
      "The four buckets of mechanism — hardware, cloud, intelligence, and the human layer — each judged by the claims it can test, the evidence it produces, what it costs to implement, and how it fails.",
    order: 2,
    prerequisiteModuleIds: ["v-why", "v-scoping"],
    itemIds: [
      "v-mechanism-effective",
      "v-mechanism-privacy",
      "v-hw-attestation",
      "v-hw-claim",
      "v-hw-trusted-statement",
      "v-hw-accounting",
      "v-hw-measuring-use",
      "v-hw-authorization",
      "v-hw-where-trust-lives",
      "v-hw-reconstructing-run",
      "v-hw-policy-studio",
      "v-cloud",
      "v-cloud-customer-identification",
      "v-cloud-detection-gaps",
      "v-cloud-evidence",
      "v-intel-intro",
      "v-intel-signatures",
      "v-intel-anchor",
      "v-intel-assessment",
      "v-intel-institutions",
      "v-intel-action",
      "v-human-intro",
      "v-human-insiders",
      "v-human-reporting-protection",
      "v-human-audits-inspections",
      "v-human-institutions",
    ],
  },
  {
    id: "v-covert",
    slug: "covert-development",
    trackId: "verification",
    title: "Architecture and Limitations of Low-Trust AI Compute Verification",
    summary:
      "How the requirements of an international AI agreement might be translated into a technical verification system: the assumptions, design choices, and unresolved problems involved in verifying AI compute use under conditions of limited trust between the parties.",
    order: 3,
    prerequisiteModuleIds: ["v-why", "v-scoping", "v-infrastructure"],
    itemIds: ["v-covert-system-overview"],
  },
  {
    id: "v-capstone",
    slug: "capstone",
    trackId: "verification",
    title: "Capstone: what would be enough for a three-month emergency pause?",
    summary:
      "Putting it all together — then the feasibility judgments the capstone runs on: the four metrics, and how to do the research they ask for, from a practising AI governance researcher. Then the capstone itself: layer the imperfect mechanisms into a regime you can defend, and say where to go from here.",
    order: 4,
    prerequisiteModuleIds: ["v-why", "v-scoping", "v-infrastructure", "v-covert"],
    itemIds: [
      "v-capstone-together",
      "v-capstone-feasibility",
      "v-research-tips",
      "v-capstone-project",
      "v-capstone-next-steps",
    ],
  },
];

export const verificationLessons: Lesson[] = [
  {
    id: "v-scoping-intro",
    slug: "scoping-intro",
    moduleId: "v-scoping",
    title: "1.0 Introduction: what kind of policy are we trying to verify?",
    contentRef: "verification/scoping-intro",
    estimatedMinutes: 5,
  },
  {
    id: "v-scoping-thresholds",
    slug: "scoping-thresholds",
    moduleId: "v-scoping",
    sectionItemId: "v-scoping-intro",
    title: "1.0.1 Drawing the Line: Compute vs. Capability",
    contentRef: "verification/scoping-thresholds",
    estimatedMinutes: 5,
  },
  {
    id: "v-scoping-effective-feasible",
    slug: "scoping-effective-feasible",
    moduleId: "v-scoping",
    sectionItemId: "v-scoping-intro",
    title: "1.0.2 Policies must be effective and feasible",
    contentRef: "verification/scoping-effective-feasible",
    estimatedMinutes: 35,
  },
  {
    id: "v-scoping-anatomy",
    slug: "scoping-anatomy",
    moduleId: "v-scoping",
    title: "1.1 Anatomy of a (pause) agreement",
    contentRef: "verification/scoping-anatomy",
    estimatedMinutes: 55,
  },
  {
    id: "v-scoping-actors",
    slug: "scoping-actors",
    moduleId: "v-scoping",
    title: "1.2 Actors: who does the treaty rely upon, apply to, and constrain?",
    contentRef: "verification/scoping-actors",
    estimatedMinutes: 35,
  },
  {
    id: "v-scoping-upstream-downstream",
    slug: "scoping-upstream-downstream",
    moduleId: "v-scoping",
    title: "1.3 Upstream and downstream",
    contentRef: "verification/scoping-upstream-downstream",
    estimatedMinutes: 10,
  },
  {
    id: "v-context-distiller",
    slug: "context-distiller",
    moduleId: "v-scoping",
    sectionItemId: "v-scoping-upstream-downstream",
    title: "1.3.1 Context distiller",
    contentRef: "verification/context-distiller",
    estimatedMinutes: 15,
  },
  {
    id: "v-mechanism-effective",
    slug: "mechanism-effective",
    moduleId: "v-infrastructure",
    title: "2.0 What makes a verification mechanism effective?",
    contentRef: "verification/mechanism-effective",
    estimatedMinutes: 15,
  },
  {
    id: "v-mechanism-privacy",
    slug: "mechanism-privacy",
    moduleId: "v-infrastructure",
    sectionItemId: "v-mechanism-effective",
    title: "2.0.1 Privacy-Preserving Mechanisms",
    contentRef: "verification/mechanism-privacy",
    estimatedMinutes: 10,
  },
  {
    id: "v-human-intro",
    slug: "human-intro",
    moduleId: "v-infrastructure",
    title: "2.4 The human layer",
    contentRef: "verification/human-intro",
  },
  {
    id: "v-human-insiders",
    slug: "human-insiders",
    moduleId: "v-infrastructure",
    sectionItemId: "v-human-intro",
    title: "2.4.1 Insiders and human sources",
    contentRef: "verification/human-insiders",
    estimatedMinutes: 30,
  },
  {
    id: "v-human-reporting-protection",
    slug: "human-reporting-protection",
    moduleId: "v-infrastructure",
    sectionItemId: "v-human-intro",
    title: "2.4.2 Reporting and protection",
    contentRef: "verification/human-reporting-protection",
    estimatedMinutes: 60,
  },
  {
    id: "v-human-audits-inspections",
    slug: "human-audits-inspections",
    moduleId: "v-infrastructure",
    sectionItemId: "v-human-intro",
    title: "2.4.3 Audits and inspections",
    contentRef: "verification/human-audits-inspections",
    estimatedMinutes: 30,
  },
  {
    id: "v-human-institutions",
    slug: "human-institutions",
    moduleId: "v-infrastructure",
    sectionItemId: "v-human-intro",
    title: "2.4.4 Institutions and policy judgment",
    contentRef: "verification/human-institutions",
    estimatedMinutes: 25,
  },
  {
    id: "v-covert-system-overview",
    slug: "low-trust-compute-verification",
    moduleId: "v-covert",
    title:
      "3.0 A system overview for near-term, low-trust AI compute verification",
    contentRef: "verification/covert-system-overview",
    estimatedMinutes: 15,
  },
  {
    id: "v-capstone-together",
    slug: "putting-it-all-together",
    moduleId: "v-capstone",
    title: "4.0 Putting it All Together",
    contentRef: "verification/capstone-together",
    estimatedMinutes: 5,
  },
  {
    id: "v-capstone-feasibility",
    slug: "capstone-feasibility",
    moduleId: "v-capstone",
    title: "4.1 Feasibility Judgments",
    contentRef: "verification/capstone-feasibility",
    estimatedMinutes: 120,
  },
  {
    id: "v-capstone-project",
    slug: "capstone-project",
    moduleId: "v-capstone",
    title: "4.2 Capstone project",
    contentRef: "verification/capstone-project",
  },
  {
    id: "v-capstone-next-steps",
    slug: "capstone-next-steps",
    moduleId: "v-capstone",
    title: "Congratulations",
    contentRef: "verification/capstone-next-steps",
    completion: true,
  },
  {
    id: "v-hw-attestation",
    slug: "hardware-attestation",
    moduleId: "v-infrastructure",
    title: "2.1 Hardware",
    contentRef: "verification/hardware-attestation",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-claim",
    slug: "hardware-claim",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.1 Start with the claim, not the mechanism",
    contentRef: "verification/hardware-claim",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-trusted-statement",
    slug: "hardware-trusted-statement",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.2 From a chip to a trusted statement",
    contentRef: "verification/hardware-trusted-statement",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-accounting",
    slug: "hardware-accounting",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.3 Accounting for hardware: identity, location, topology, and completeness",
    contentRef: "verification/hardware-accounting",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-measuring-use",
    slug: "hardware-measuring-use",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.4 Measuring and classifying use",
    contentRef: "verification/hardware-measuring-use",
    estimatedMinutes: 10,
  },
  {
    id: "v-hw-authorization",
    slug: "hardware-authorization",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.5 Authorization, licensing, and control",
    contentRef: "verification/hardware-authorization",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-where-trust-lives",
    slug: "hardware-where-trust-lives",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.6 Where should trust live?",
    contentRef: "verification/hardware-where-trust-lives",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-reconstructing-run",
    slug: "hardware-reconstructing-run",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    optional: true,
    title: "2.1.7 Reconstructing a declared training run",
    contentRef: "verification/hardware-reconstructing-run",
    estimatedMinutes: 5,
  },
  {
    id: "v-hw-policy-studio",
    slug: "hardware-policy-studio",
    moduleId: "v-infrastructure",
    sectionItemId: "v-hw-attestation",
    title: "2.1.8 Policy judgment: what role should hardware play?",
    contentRef: "verification/hardware-policy-studio",
    estimatedMinutes: 130,
  },
  {
    id: "v-welcome",
    slug: "welcome",
    moduleId: "v-why",
    title: "0.0 Welcome",
    contentRef: "verification/welcome",
    estimatedMinutes: 5,
    unchunked: true,
  },
  {
    id: "v-introduction",
    slug: "introduction",
    moduleId: "v-why",
    title: "0.1 Introduction: Why Should You Care About AI Verification?",
    contentRef: "verification/introduction",
    estimatedMinutes: 25,
  },
  {
    id: "v-prevention",
    slug: "prevention-is-invisible",
    moduleId: "v-why",
    sectionItemId: "v-introduction",
    title: "0.1.1 Why Securitizing AI Is Difficult but Necessary",
    contentRef: "verification/prevention",
    estimatedMinutes: 5,
  },
  {
    id: "v-theories-of-change",
    slug: "theories-of-change",
    moduleId: "v-why",
    sectionItemId: "v-introduction",
    title: "0.1.2 We Need More Theories of Change",
    contentRef: "verification/theories-of-change",
    estimatedMinutes: 6,
  },
  {
    id: "v-intuitions",
    slug: "building-intuitions",
    moduleId: "v-why",
    title: "0.2 Building Verification Intuitions",
    contentRef: "verification/intuitions",
    estimatedMinutes: 200,
  },
  {
    id: "v-precedents",
    slug: "precedents",
    moduleId: "v-why",
    title: "0.3 History, Precedents, Parallels",
    contentRef: "verification/precedents",
    estimatedMinutes: 60,
  },
  {
    id: "v-strategic-foundations",
    slug: "strategic-foundations",
    moduleId: "v-why",
    title: "0.4 Strategic Foundations",
    contentRef: "verification/strategic-foundations",
    estimatedMinutes: 80,
    optional: true,
    unchunked: true,
  },
  {
    id: "v-interactive-map",
    slug: "interactive-map",
    moduleId: "v-scoping",
    sectionItemId: "v-scoping-actors",
    title: "1.2.1 Geographic supply-chain map",
    contentRef: "verification/interactive-map",
    estimatedMinutes: 15,
  },
  {
    id: "v-actor-edges",
    slug: "actor-edges",
    moduleId: "v-scoping",
    sectionItemId: "v-scoping-actors",
    title: "1.2.2 Who can prove what",
    contentRef: "verification/actor-edges",
    estimatedMinutes: 20,
  },
  {
    id: "v-cloud",
    slug: "cloud",
    moduleId: "v-infrastructure",
    title: "2.2.1 Provider records and workload observables",
    contentRef: "verification/cloud",
    estimatedMinutes: 38,
    sidebarGroupTitle: "2.2 Cloud",
  },
  {
    id: "v-cloud-customer-identification",
    slug: "cloud-customer-identification",
    moduleId: "v-infrastructure",
    sectionItemId: "v-cloud",
    title: "2.2.2 Customer identification and ongoing monitoring",
    contentRef: "verification/cloud-customer-identification",
    estimatedMinutes: 22,
  },
  {
    id: "v-cloud-detection-gaps",
    slug: "cloud-detection-gaps",
    moduleId: "v-infrastructure",
    sectionItemId: "v-cloud",
    title: "2.2.3 Detection gaps and policy limits",
    contentRef: "verification/cloud-detection-gaps",
    estimatedMinutes: 30,
  },
  {
    id: "v-cloud-evidence",
    slug: "cloud-evidence",
    moduleId: "v-infrastructure",
    sectionItemId: "v-cloud",
    title: "2.2.4 Interpreting cloud evidence",
    contentRef: "verification/cloud-evidence",
    estimatedMinutes: 30,
  },
  {
    id: "v-intel-intro",
    slug: "intelligence-intro",
    moduleId: "v-infrastructure",
    title: "2.3 Intelligence",
    contentRef: "verification/intelligence-intro",
    estimatedMinutes: 10,
  },
  {
    id: "v-intel-signatures",
    slug: "intelligence-signatures",
    moduleId: "v-infrastructure",
    sectionItemId: "v-intel-intro",
    title: "2.3.1 Observable signatures of undeclared AI development",
    contentRef: "verification/intelligence-signatures",
    estimatedMinutes: 75,
  },
  {
    id: "v-intel-anchor",
    slug: "intelligence-anchor",
    moduleId: "v-infrastructure",
    sectionItemId: "v-intel-intro",
    title: "2.3.2 The empirical anchor: intelligence identifies, the regime resolves",
    contentRef: "verification/intelligence-anchor",
    estimatedMinutes: 60,
  },
  {
    id: "v-intel-assessment",
    slug: "intelligence-assessment",
    moduleId: "v-infrastructure",
    sectionItemId: "v-intel-intro",
    title: "2.3.3 From signal to intelligence assessment",
    contentRef: "verification/intelligence-assessment",
    estimatedMinutes: 80,
  },
  {
    id: "v-intel-institutions",
    slug: "intelligence-institutions",
    moduleId: "v-infrastructure",
    sectionItemId: "v-intel-intro",
    title: "2.3.4 Intelligence institutions and treaty design",
    contentRef: "verification/intelligence-institutions",
    estimatedMinutes: 75,
  },
  {
    id: "v-intel-action",
    slug: "intelligence-action",
    moduleId: "v-infrastructure",
    sectionItemId: "v-intel-intro",
    title: "2.3.5 From intelligence lead to verification action",
    contentRef: "verification/intelligence-action",
    estimatedMinutes: 180,
  },
  {
    id: "v-research-tips",
    slug: "how-to-do-research-well",
    moduleId: "v-capstone",
    sectionItemId: "v-capstone-feasibility",
    title: "4.1.1 How to Do Research Well",
    contentRef: "verification/research-tips",
    estimatedMinutes: 25,
    unchunked: true,
    plainLists: true,
  },
];

export const verificationPaperIds: string[] = [
  "v-paper-scher-treaty",
];

export const verificationUnitOfLesson: Record<string, string> = {
  "v-welcome": "0.0",
  "v-introduction": "0.1",
  "v-prevention": "0.1",
  "v-theories-of-change": "0.1",
  "v-intuitions": "0.2",
  "v-precedents": "0.3",
  "v-strategic-foundations": "0.4",
  "v-scoping-intro": "1.0",
  "v-scoping-thresholds": "1.0",
  "v-scoping-effective-feasible": "1.0",
  "v-scoping-anatomy": "1.1",
  "v-scoping-actors": "1.2",
  "v-interactive-map": "1.2",
  "v-actor-edges": "1.2",
  "v-scoping-upstream-downstream": "1.3",
  "v-context-distiller": "1.3",
  "v-mechanism-effective": "2.0",
  "v-mechanism-privacy": "2.0",
  "v-hw-attestation": "2.1",
  "v-hw-claim": "2.1",
  "v-hw-trusted-statement": "2.1",
  "v-hw-accounting": "2.1",
  "v-hw-measuring-use": "2.1",
  "v-hw-authorization": "2.1",
  "v-hw-where-trust-lives": "2.1",
  "v-hw-reconstructing-run": "2.1",
  "v-hw-policy-studio": "2.1",
  "v-cloud": "2.2",
  "v-cloud-customer-identification": "2.2",
  "v-cloud-detection-gaps": "2.2",
  "v-cloud-evidence": "2.2",
  "v-intel-intro": "2.3",
  "v-intel-signatures": "2.3",
  "v-intel-anchor": "2.3",
  "v-intel-assessment": "2.3",
  "v-intel-institutions": "2.3",
  "v-intel-action": "2.3",
  "v-human-intro": "2.4",
  "v-human-insiders": "2.4",
  "v-human-reporting-protection": "2.4",
  "v-human-audits-inspections": "2.4",
  "v-human-institutions": "2.4",
  "v-covert-system-overview": "3.0",
  "v-capstone-together": "4.0",
  "v-capstone-feasibility": "4.1",
  "v-research-tips": "4.1",
  "v-capstone-project": "4.2",
  "v-capstone-next-steps": "4.3",
};

export const verificationUnitMeta: Record<
  string,
  { title: string; kind: string; mins: string; optional?: boolean }
> = {
  "0.0": { title: "Welcome", kind: "explainer", mins: "5–10 min" },
  "0.1": { title: "How the risk looks like?", kind: "explainer", mins: "15–20 min" },
  "0.2": { title: "Building Verification Intuitions", kind: "exercise", mins: "self-paced" },
  "0.3": { title: "History, Precedents, Parallels", kind: "interactive", mins: "20–25 min" },
  "0.4": { title: "Strategic Foundations", kind: "reading", mins: "self-paced", optional: true },
  "1.0": { title: "Introduction: what kind of policy are we trying to verify?", kind: "explainer", mins: "15–20 min" },
  "1.1": { title: "Anatomy of a pause agreement", kind: "interactive", mins: "20–25 min" },
  "1.2": { title: "Actors", kind: "interactive", mins: "25–30 min" },
  "1.3": { title: "Upstream and downstream", kind: "explainer", mins: "10–15 min" },
  "2.0": { title: "Confidentiality vs. verifiability", kind: "explainer", mins: "15–20 min" },
  "2.1": { title: "Hardware", kind: "explainer", mins: "165–180 min" },
  "2.2": { title: "Cloud", kind: "reading + exercise", mins: "120 min" },
  "2.3": { title: "Intelligence", kind: "explainer", mins: "35–45 min" },
  "2.4": { title: "Human", kind: "explainer", mins: "120 min" },
  "3.0": { title: "What is covert development?", kind: "explainer", mins: "10–15 min" },
  "3.1": { title: "How could a determined actor cheat?", kind: "interactive", mins: "30–40 min" },
  "3.2": { title: "Red team / blue team", kind: "exercise", mins: "45–60 min" },
  "4.0": { title: "Putting it All Together", kind: "explainer", mins: "5–10 min" },
  "4.1": { title: "Feasibility Judgments", kind: "reading + exercise", mins: "120–150 min" },
  "4.2": { title: "Capstone", kind: "capstone", mins: "4–8 hrs" },
  "4.3": { title: "Where to go from here", kind: "explainer", mins: "15–20 min" },
};

export const verificationModuleMeta: Record<
  string,
  { n: number; slug: string; title: string; glyph: string; week: string; status: string }
> = {
  "v-why": { n: 0, slug: "foundations", title: "Foundations", glyph: "✧", week: "week 1", status: "drafted" },
  "v-scoping": { n: 1, slug: "policy-and-actors", title: "Policy and actors", glyph: "❖", week: "weeks 2–3", status: "drafted" },
  "v-infrastructure": { n: 2, slug: "evidence-streams", title: "Evidence streams", glyph: "⚙", week: "weeks 4–8", status: "notes complete" },
  "v-covert": { n: 3, slug: "covert-development", title: "Covert development", glyph: "⚠", week: "week 9", status: "taxonomy complete" },
  "v-capstone": { n: 4, slug: "capstone", title: "Trust without trust", glyph: "✦", week: "week 10", status: "framing complete" },
};
