/**
 * Human-authored mechanism deck from tracksprogramplayground's
 * "Five Maps of the Evidence" prototype. The placements are the course's
 * judgment calls, not the cited authors'.
 */
export type EvidenceMapKey =
  | "layer"
  | "access"
  | "goal"
  | "lifecycle"
  | "adversary";

export interface EvidenceMechanism {
  id: string;
  name: string;
  description: string;
  friction?: string;
}

export interface EvidenceGroup {
  name: string;
  sub: string;
  ids: string[];
  empty?: string;
}

export interface EvidenceTaxonomy {
  key: EvidenceMapKey;
  label: string;
  question: string;
  lineage: string;
  strengths: string[];
  limits: string[];
  groups: EvidenceGroup[];
}

export const EVIDENCE_MECHANISMS: EvidenceMechanism[] = [
  {
    id: "attest",
    name: "On-chip attestation",
    description:
      "A chip signs statements about its identity and configuration, anchored in a hardware root of trust.",
    friction:
      "Attestation is only as good as its key, and the key sits in silicon the adversary may own. Commercial secure boot protects a machine's owner; verification asks it to catch the owner.",
  },
  {
    id: "meter",
    name: "Compute metering",
    description:
      "Firmware keeps a tamper-evident total of how much computation an accelerator has performed.",
    friction:
      "The sensor is silicon, but metering only becomes evidence when someone collects and audits the totals. It also inherits attestation's owner-as-adversary problem.",
  },
  {
    id: "registry",
    name: "Chip registry and supply-chain tracking",
    description:
      "A ledger of who holds which accelerators, updated at manufacture, sale and resale.",
    friction:
      "A registry is a database and a legal reporting duty, not a device. Everything that makes it work is institutional: customs enforcement, resale reporting and audit rights.",
  },
  {
    id: "kyc",
    name: "Cloud KYC",
    description:
      "Providers verify customer identity and beneficial ownership before selling large amounts of compute.",
    friction:
      "The cooperation comes from companies under domestic law, not from a rival state under a treaty. It needs no consent from the target state, which makes it a poor fit for every access bucket.",
  },
  {
    id: "accounting",
    name: "Cloud compute accounting",
    description:
      "Provider-side logs of which accounts ran how much compute, on what hardware.",
    friction:
      "Generated by hardware, held by a provider and disclosed under whatever legal regime applies. It serves nearly every policy goal and is the least stable placement in the deck.",
  },
  {
    id: "satellite",
    name: "Satellite imagery",
    description:
      "Thermal signatures and construction footprints of data centers, visible from orbit.",
    friction:
      "Construction is visible before a run, heat during it, and neither reveals workloads. It is a two-stage sensor forced into one lifecycle bucket.",
  },
  {
    id: "energy",
    name: "Power-draw monitoring",
    description:
      "Grid-level and facility-level electricity data used as a proxy for large training activity.",
    friction:
      "Grid-scale data can be gathered remotely. Facility-level metering needs host cooperation. One mechanism falls into two access buckets depending on the resolution required.",
  },
  {
    id: "sigint",
    name: "Signals intelligence and cyber",
    description:
      "Intercepted communications and network intrusion run by state intelligence agencies.",
    friction:
      "Effective and unacknowledgeable. Intrusion can produce private confidence but rarely shareable proof without exposing sources and methods.",
  },
  {
    id: "osint",
    name: "Open-source intelligence",
    description:
      "Procurement records, customs data, job postings, publications and financial filings.",
  },
  {
    id: "inspect",
    name: "On-site inspections",
    description:
      "Negotiated visits to declared facilities, usually under managed-access rules.",
    friction:
      "Filed under human, but most of an inspector's work is reading hardware. The layer map sorts by who carries the evidence, not what the evidence is.",
  },
  {
    id: "interview",
    name: "Staff interviews",
    description:
      "Structured questioning of researchers and engineers, typically during inspections.",
  },
  {
    id: "whistle",
    name: "Whistleblower channels",
    description:
      "Protected routes for insiders to report violations, plus the machinery to corroborate reports.",
    friction:
      "They need no consent from the target state, but they do need protected channels and legal shelter negotiated in advance. States can also imprison whistleblowers, so the adversary grade is probabilistic.",
  },
];

export const EVIDENCE_TAXONOMIES: EvidenceTaxonomy[] = [
  {
    key: "layer",
    label: "By layer",
    question: "Where does the evidence come from, and who controls the sensor?",
    lineage:
      "Written mostly by technical AI governance researchers for institution designers and engineers deciding who must build and operate each stream.",
    strengths: [
      "Maps onto real institutions: chipmakers, cloud providers, intelligence agencies and inspectorates.",
      "Makes redundancy reasoning natural: independent layers force an evader to attack several streams.",
      "Concrete to teach and staff; each layer is a profession.",
    ],
    limits: [
      "Mechanisms straddle layers: compute accounting is hardware telemetry read through a cloud provider.",
      "It is silent on political cost: unilateral espionage and negotiated access sit side by side.",
      "Layers can look independent while sharing the same upstream firms.",
    ],
    groups: [
      { name: "Hardware", sub: "the silicon itself", ids: ["attest", "meter", "registry"] },
      { name: "Cloud", sub: "the provider layer", ids: ["kyc", "accounting"] },
      { name: "Intelligence", sub: "what a state can see uninvited", ids: ["satellite", "energy", "sigint", "osint"] },
      { name: "Human", sub: "people who know things", ids: ["inspect", "interview", "whistle"] },
    ],
  },
  {
    key: "access",
    label: "By access",
    question: "What must the target concede before this evidence can exist?",
    lineage:
      "The arms-control tradition of IAEA safeguards and the CWC, written for negotiators deciding what a treaty can actually demand. Wasil et al. (2024) is the clearest AI example.",
    strengths: [
      "Prices sovereignty directly: what each stream costs to obtain and what works before an agreement exists.",
      "Sequences the regime: unilateral streams work now, treaty access comes later, hardware takes years.",
      "Inherits tested legal language around managed access and non-interference.",
    ],
    limits: [
      "Access is a spectrum, not three buckets.",
      "Categories drift as technology moves; a site visit today may become a remote proof.",
      "It says nothing about what the evidence proves, only how hard it is to get.",
    ],
    groups: [
      { name: "National technical means", sub: "no cooperation needed", ids: ["satellite", "energy", "sigint", "osint", "whistle"] },
      { name: "Negotiated access", sub: "the target must agree", ids: ["inspect", "interview", "accounting", "kyc"] },
      { name: "Pre-installed governance tech", sub: "built in years ahead", ids: ["attest", "meter", "registry"] },
    ],
  },
  {
    key: "goal",
    label: "By goal",
    question: "Which claim in the agreement is this evidence supposed to check?",
    lineage:
      "Written by policy analysts working backward from a proposed rule. Scher and Thiergart (2024) start from the agreement and ask what could verify it.",
    strengths: [
      "Starts where policymakers start: with the rule.",
      "Exposes coverage gaps per clause.",
      "Forces the question: verify what, exactly, and against whom?",
    ],
    limits: [
      "The same mechanism reappears under several goals, so the map duplicates instead of partitions.",
      "It redraws whenever the policy menu changes.",
      "It hides shared infrastructure and single points of failure.",
    ],
    groups: [
      { name: "Detect covert training runs", sub: "find what was never declared", ids: ["satellite", "energy", "sigint", "osint", "whistle", "meter"] },
      { name: "Verify declared runs comply", sub: "check what was admitted to", ids: ["attest", "meter", "accounting", "inspect", "interview"] },
      { name: "Track where the chips are", sub: "account for the stock", ids: ["registry", "kyc", "osint", "inspect"] },
    ],
  },
  {
    key: "lifecycle",
    label: "By lifecycle",
    question: "When in the life of a model does the evidence attach?",
    lineage:
      "Compute-governance research for engineers and regulators deciding where in the pipeline to attach controls, including Shavit (2023) and Sastry, Heim et al. (2024).",
    strengths: [
      "Shows which evidence must be captured live because it cannot be recovered later.",
      "Sequences enforcement by cost: acquisition is cheaper to catch than a live run.",
      "Each stage is a distinct engineering surface.",
    ],
    limits: [
      "Assumes the current pipeline shape of giant pretraining runs on registered accelerators.",
      "Human and intelligence streams watch institutions, not pipeline stages.",
      "The empty deployment column is an honest gap the map cannot fix.",
    ],
    groups: [
      { name: "Before a run", sub: "chips made, sold and moved", ids: ["registry", "kyc"] },
      { name: "During a run", sub: "while the compute burns", ids: ["attest", "meter", "accounting", "energy", "satellite"] },
      { name: "After deployment", sub: "models loose in the world", ids: [], empty: "None of the twelve. Third-party evaluations, incident reporting and observing outputs are a toolkit this deck barely touches. Noticing the empty column is the point." },
      { name: "Any stage", sub: "watching people, not pipelines", ids: ["osint", "sigint", "inspect", "interview", "whistle"] },
    ],
  },
  {
    key: "adversary",
    label: "By adversary",
    question: "Who is this evidence still good against?",
    lineage:
      "Arms-control practice separates monitoring a partner from catching a determined cheat; security researchers apply the same owner-as-adversary test to AI mechanisms.",
    strengths: [
      "Grades strength, not just kind.",
      "Forces the threat model onto every card.",
      "Exposes the commercial-security trap: tools built to protect the owner are asked to catch the owner.",
    ],
    limits: [
      "Robustness is a spectrum pretending to be three buckets.",
      "Read carelessly, it breeds nihilism; combinations of streams can survive where single streams do not.",
      "It says nothing about cost, legality or who operates the stream.",
    ],
    groups: [
      { name: "Cooperative target", sub: "verifies good faith, not bad", ids: ["inspect", "interview"] },
      { name: "Cheating company", sub: "assumes functioning states above it", ids: ["attest", "meter", "registry", "kyc", "accounting"] },
      { name: "Evading state", sub: "no consent, no permission", ids: ["satellite", "energy", "sigint", "osint", "whistle"] },
    ],
  },
];
