import type { Lesson, Module, Track } from "@/lib/content/types";

// Control and Governance are intentionally empty for now — just an intro blurb,
// ready for real curriculum. The "Example" track is a fully-built demo of every
// feature (the four content types, each exercise type, an end-of-module
// assessment, and a cross-module prerequisite). Replace lorem with real content;
// see AUTHORING.md.

export const tracks: Track[] = [
  {
    id: "control",
    slug: "control",
    title: "AI Control",
    shortTitle: "Control",
    description:
      "Hands-on technical track on controlling and evaluating AI systems. Module 1 works through Redwood Research's \"AI Control: Improving Safety Despite Intentional Subversion\" paper verbatim; later modules will turn it into interactive exercises and demos.",
    kind: "technical",
    moduleIds: ["c-paper"],
    prerequisiteEnforcement: "hard",
  },
  {
    id: "governance",
    slug: "governance",
    title: "AI Governance & Policy",
    shortTitle: "Governance",
    description:
      "Policy-oriented track with real writing deliverables. Lorem ipsum dolor sit amet, consectetur adipiscing elit — content coming soon.",
    kind: "governance",
    moduleIds: [],
    prerequisiteEnforcement: "soft",
  },
  {
    id: "example",
    slug: "example",
    title: "Example Track",
    shortTitle: "Example",
    description:
      "A demo track showing every feature in one place — the four content types, each exercise type, an end-of-module assessment, and a cross-module prerequisite. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    kind: "example",
    moduleIds: ["ex-content", "ex-assess"],
    prerequisiteEnforcement: "soft",
    estimatedHours: 1,
  },
];

export const modules: Module[] = [
  {
    id: "c-paper",
    slug: "ai-control-paper",
    trackId: "control",
    title: "The AI Control paper",
    summary:
      "A verbatim, sublesson-by-section reproduction of Redwood Research's \"AI Control: Improving Safety Despite Intentional Subversion\" (arXiv:2312.06942) — the main text plus three optional appendices.",
    order: 1,
    prerequisiteModuleIds: [],
    lessonIds: [
      "c-paper-l1",
      "c-paper-l2",
      "c-paper-l3",
      "c-paper-l4",
      "c-paper-l6",
      "c-paper-l8",
      "c-paper-l9",
      "c-paper-l10",
    ],
    estimatedMinutes: 95,
  },
  {
    id: "ex-content",
    slug: "content-types",
    trackId: "example",
    title: "Content types",
    summary:
      "Lorem ipsum dolor sit amet — text, video, callouts, an interactive demo, and exercises, all inside lessons.",
    order: 1,
    prerequisiteModuleIds: [],
    lessonIds: ["ex-content-l1", "ex-content-l2"],
    furtherReadingTopics: ["alignment", "interpretability"],
    estimatedMinutes: 25,
  },
  {
    id: "ex-assess",
    slug: "assessment-and-prerequisites",
    trackId: "example",
    title: "Assessment & prerequisites",
    summary:
      "Lorem ipsum — this module requires the first one (a soft prerequisite) and ends with a written assessment.",
    order: 2,
    prerequisiteModuleIds: ["ex-content"],
    lessonIds: ["ex-assess-l1"],
    assessmentId: "ex-assessment",
    furtherReadingTopics: ["governance"],
    estimatedMinutes: 20,
  },
];

export const lessons: Lesson[] = [
  {
    id: "c-paper-l1",
    slug: "abstract-and-introduction",
    moduleId: "c-paper",
    title: "Abstract & Introduction",
    order: 1,
    contentRef: "c-paper-l1",
    estimatedMinutes: 8,
  },
  {
    id: "c-paper-l2",
    slug: "setting",
    moduleId: "c-paper",
    title: "Setting",
    order: 2,
    contentRef: "c-paper-l2",
    estimatedMinutes: 15,
  },
  {
    id: "c-paper-l3",
    slug: "results-baselines-and-trusted-monitoring",
    moduleId: "c-paper",
    title: "Results I — Baselines & Trusted Monitoring",
    order: 3,
    contentRef: "c-paper-l3",
    estimatedMinutes: 15,
  },
  {
    id: "c-paper-l4",
    slug: "results-defer-untrusted-monitoring-and-trusted-editing",
    moduleId: "c-paper",
    title: "Results II — Defer to Trusted, Untrusted Monitoring & Trusted Editing",
    order: 4,
    contentRef: "c-paper-l4",
    estimatedMinutes: 20,
  },
  {
    id: "c-paper-l6",
    slug: "discussion",
    moduleId: "c-paper",
    title: "Discussion",
    order: 5,
    contentRef: "c-paper-l6",
    estimatedMinutes: 12,
  },
  {
    id: "c-paper-l8",
    slug: "appendix-glossary",
    moduleId: "c-paper",
    title: "Glossary",
    order: 6,
    contentRef: "c-paper-l8",
    estimatedMinutes: 6,
    optional: true,
  },
  {
    id: "c-paper-l9",
    slug: "appendix-summary-statistics-justification",
    moduleId: "c-paper",
    title: "Justification of Summary Statistics Access",
    order: 7,
    contentRef: "c-paper-l9",
    estimatedMinutes: 8,
    optional: true,
  },
  {
    id: "c-paper-l10",
    slug: "appendix-black-box-protocol-assumption",
    moduleId: "c-paper",
    title: "The Black-Box Protocol Assumption",
    order: 8,
    contentRef: "c-paper-l10",
    estimatedMinutes: 10,
    optional: true,
  },
  {
    id: "ex-content-l1",
    slug: "text-video-callouts",
    moduleId: "ex-content",
    title: "Text, video & callouts",
    order: 1,
    contentRef: "ex-content-l1",
    estimatedMinutes: 8,
  },
  {
    id: "ex-content-l2",
    slug: "demos-and-exercises",
    moduleId: "ex-content",
    title: "Demos & exercises",
    order: 2,
    contentRef: "ex-content-l2",
    estimatedMinutes: 10,
  },
  {
    id: "ex-assess-l1",
    slug: "putting-it-together",
    moduleId: "ex-assess",
    title: "Putting it together",
    order: 1,
    contentRef: "ex-assess-l1",
    estimatedMinutes: 7,
  },
];
