import type { Lesson, Module, Track, Unit } from "@/lib/content/types";

// Control and Governance are intentionally empty for now — just an intro blurb,
// ready for real curriculum. The "Example" track is a fully-built demo of every
// feature (the four content types, each exercise type, an end-of-module
// assessment, and a cross-module prerequisite). Replace lorem with real content;
// see AUTHORING.md.

export const tracks: Track[] = [
  {
    id: "control",
    slug: "control",
    title: "AI Control",
    shortTitle: "Control",
    description:
      "Hands-on technical track on controlling and evaluating AI systems. The introductory module works through Redwood Research's \"AI Control: Improving Safety Despite Intentional Subversion\" paper and then rebuilds its trusted-monitoring result as an interactive, model-backed demo.",
    kind: "technical",
    moduleIds: ["c-intro"],
    prerequisiteEnforcement: "hard",
  },
  {
    id: "governance",
    slug: "governance",
    title: "AI Governance & Policy",
    shortTitle: "Governance",
    description:
      "Policy-oriented track with real writing deliverables. Lorem ipsum dolor sit amet, consectetur adipiscing elit — content coming soon.",
    kind: "governance",
    moduleIds: [],
    prerequisiteEnforcement: "soft",
  },
  {
    id: "example",
    slug: "example",
    title: "Example Track",
    shortTitle: "Example",
    description:
      "A demo track showing every feature in one place — the four content types, each exercise type, an end-of-module assessment, and a cross-module prerequisite. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    kind: "example",
    moduleIds: ["ex-content", "ex-assess"],
    prerequisiteEnforcement: "soft",
    estimatedHours: 1,
  },
];

export const modules: Module[] = [
  {
    id: "c-intro",
    slug: "introduction",
    trackId: "control",
    title: "Introduction, overview, and threat modeling",
    summary:
      "The foundation for the track: Redwood Research's \"AI Control: Improving Safety Despite Intentional Subversion\" paper reproduced in full, then rebuilt as an interactive, calibrated demo you can play with.",
    order: 1,
    prerequisiteModuleIds: [],
    unitIds: ["c-u-paper", "c-u-demo"],
    estimatedMinutes: 190,
  },
  {
    id: "ex-content",
    slug: "content-types",
    trackId: "example",
    title: "Content types",
    summary:
      "Lorem ipsum dolor sit amet — text, video, callouts, an interactive demo, and exercises, all inside lessons.",
    order: 1,
    prerequisiteModuleIds: [],
    unitIds: ["ex-content-u"],
    furtherReadingTopics: ["alignment", "interpretability"],
    estimatedMinutes: 25,
  },
  {
    id: "ex-assess",
    slug: "assessment-and-prerequisites",
    trackId: "example",
    title: "Assessment & prerequisites",
    summary:
      "Lorem ipsum — this module requires the first one (a soft prerequisite) and ends with a written assessment.",
    order: 2,
    prerequisiteModuleIds: ["ex-content"],
    unitIds: ["ex-assess-u"],
    assessmentId: "ex-assessment",
    furtherReadingTopics: ["governance"],
    estimatedMinutes: 20,
  },
];

export const units: Unit[] = [
  {
    id: "c-u-paper",
    slug: "the-control-paper",
    moduleId: "c-intro",
    title: "The control paper",
    summary:
      "Redwood Research's \"AI Control: Improving Safety Despite Intentional Subversion\" (arXiv:2312.06942) reproduced sublesson-by-section — the main text, then three optional appendices.",
    order: 1,
    lessonIds: [
      "c-paper-l1",
      "c-paper-l2",
      "c-paper-l3",
      "c-paper-l4",
      "c-paper-l6",
      "c-paper-l8",
      "c-paper-l9",
      "c-paper-l10",
    ],
  },
  {
    id: "c-u-demo",
    slug: "the-demo",
    moduleId: "c-intro",
    title: "The demo",
    summary:
      "The paper's trusted-monitoring result rebuilt as an interactive game backed by a calibrated model: why a good monitor still misses attacks, why the red team plays a best response, and what deferring to the trusted model actually buys.",
    order: 2,
    lessonIds: [
      "c-game-l1",
      "c-game-l2",
      "c-game-l4",
      "c-game-l5",
      "c-game-l6",
      "c-game-l3",
      "c-game-l7",
      "c-game-l8",
    ],
  },
  {
    id: "ex-content-u",
    slug: "lessons",
    moduleId: "ex-content",
    title: "Lessons",
    order: 1,
    lessonIds: ["ex-content-l1", "ex-content-l2"],
  },
  {
    id: "ex-assess-u",
    slug: "lessons",
    moduleId: "ex-assess",
    title: "Lessons",
    order: 1,
    lessonIds: ["ex-assess-l1"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "c-paper-l1",
    slug: "abstract-and-introduction",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Abstract & Introduction",
    order: 1,
    contentRef: "c-paper-l1",
    estimatedMinutes: 8,
  },
  {
    id: "c-paper-l2",
    slug: "setting",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Setting",
    order: 2,
    contentRef: "c-paper-l2",
    estimatedMinutes: 15,
  },
  {
    id: "c-paper-l3",
    slug: "results-baselines-and-trusted-monitoring",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Results I — Baselines & Trusted Monitoring",
    order: 3,
    contentRef: "c-paper-l3",
    estimatedMinutes: 15,
  },
  {
    id: "c-paper-l4",
    slug: "results-defer-untrusted-monitoring-and-trusted-editing",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Results II — Defer to Trusted, Untrusted Monitoring & Trusted Editing",
    order: 4,
    contentRef: "c-paper-l4",
    estimatedMinutes: 20,
  },
  {
    id: "c-paper-l6",
    slug: "discussion",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Discussion",
    order: 5,
    contentRef: "c-paper-l6",
    estimatedMinutes: 12,
  },
  {
    id: "c-paper-l8",
    slug: "appendix-glossary",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Glossary",
    order: 6,
    contentRef: "c-paper-l8",
    estimatedMinutes: 6,
    optional: true,
  },
  {
    id: "c-paper-l9",
    slug: "appendix-summary-statistics-justification",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "Justification of Summary Statistics Access",
    order: 7,
    contentRef: "c-paper-l9",
    estimatedMinutes: 8,
    optional: true,
  },
  {
    id: "c-paper-l10",
    slug: "appendix-black-box-protocol-assumption",
    moduleId: "c-intro",
    unitId: "c-u-paper",
    title: "The Black-Box Protocol Assumption",
    order: 8,
    contentRef: "c-paper-l10",
    estimatedMinutes: 10,
    optional: true,
  },
  {
    id: "c-game-l1",
    slug: "why-a-good-monitor-still-misses",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Why a good monitor still misses",
    order: 1,
    contentRef: "c-game-l1",
    estimatedMinutes: 10,
  },
  {
    id: "c-game-l2",
    slug: "same-auroc-different-safety",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Same AUROC, different safety",
    order: 2,
    contentRef: "c-game-l2",
    estimatedMinutes: 12,
  },
  {
    id: "c-game-l4",
    slug: "safety-over-a-deployment-the-race",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Safety over a deployment: the race",
    order: 3,
    contentRef: "c-game-l4",
    estimatedMinutes: 12,
  },
  {
    id: "c-game-l5",
    slug: "opportunities-are-not-equal",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Opportunities are not equal",
    order: 4,
    contentRef: "c-game-l5",
    estimatedMinutes: 12,
  },
  {
    id: "c-game-l6",
    slug: "subtlety-visible-versus-reliable",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Subtlety: visible versus reliable",
    order: 5,
    contentRef: "c-game-l6",
    estimatedMinutes: 10,
  },
  {
    id: "c-game-l3",
    slug: "the-best-response-principle",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "The best-response principle",
    order: 6,
    contentRef: "c-game-l3",
    estimatedMinutes: 12,
  },
  {
    id: "c-game-l7",
    slug: "defer-to-trusted-mechanistically",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "Defer to trusted, mechanistically",
    order: 7,
    contentRef: "c-game-l7",
    estimatedMinutes: 12,
  },
  {
    id: "c-game-l8",
    slug: "the-whole-picture",
    moduleId: "c-intro",
    unitId: "c-u-demo",
    title: "The control game: the whole picture",
    order: 8,
    contentRef: "c-game-l8",
    estimatedMinutes: 12,
  },
  {
    id: "ex-content-l1",
    slug: "text-video-callouts",
    moduleId: "ex-content",
    unitId: "ex-content-u",
    title: "Text, video & callouts",
    order: 1,
    contentRef: "ex-content-l1",
    estimatedMinutes: 8,
  },
  {
    id: "ex-content-l2",
    slug: "demos-and-exercises",
    moduleId: "ex-content",
    unitId: "ex-content-u",
    title: "Demos & exercises",
    order: 2,
    contentRef: "ex-content-l2",
    estimatedMinutes: 10,
  },
  {
    id: "ex-assess-l1",
    slug: "putting-it-together",
    moduleId: "ex-assess",
    unitId: "ex-assess-u",
    title: "Putting it together",
    order: 1,
    contentRef: "ex-assess-l1",
    estimatedMinutes: 7,
  },
];
